# Generated by Django 5.2.6 on 2025-09-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
